project:
  type: website
  output-dir: docs

website:
  description: "blog de aprendizaje junto a Jose Vicente Ordonez"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "José Vicente Ordóñez"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - Default
      - brand
      - tema.scss
    css: styles.css

editor: visual

